import json,html
from pathlib import Path
R=Path(__file__).resolve().parents[1]
s=json.loads((R/'outputs/model-manifest.json').read_text());m=json.loads((R/'web/dist/assets/material-sources.json').read_text())
body='''<h1>NGORO · Catatan model</h1><p>Studi visual berdasarkan NGORO.send.dwg. Cakupan: seluruh tapak, eksterior, dan interior. Ukuran yang tidak tersedia dilengkapi secara realistis sesuai izin Bam.</p><h2>Data gambar</h2><ul><li>Tapak 90 × 80 m.</li><li>Tiga gudang, masing-masing 23 × 60 m.</li><li>Sosoran 15 × 60 m; kantor dua lantai 6 × 12 m; pos 3 × 3,5 m.</li><li>Grid rangka 6 m, kolom dan rafter nominal WF250; gording CNP125.</li></ul><h2>Batas dan asumsi</h2>'''
body+='<ul>'+''.join('<li>'+html.escape(a)+'</li>' for a in s['assumptions'])+'</ul>'
body+='''<p>SKP berisi geometri yang dapat diedit dan tekstur warna tertanam. Refleksi, normal map, kekasaran, langit, dan pencahayaan dinamis dirender oleh Three.js. Pohon, kendaraan, furnitur dan stok gudang adalah objek representatif, bukan produk spesifik.</p><h2>Pengoperasian</h2><p>Seret satu jari atau mouse untuk memutar. Gulir atau cubit untuk zoom. Dua jari atau tombol kanan mouse untuk menggeser. Setelah klik area model, W/A/S/D atau panah menggerakkan kamera. Pilih sudut interior untuk masuk ke bangunan. Kontrol atap menampilkan susunan di dalam bangunan. Mode Orbit bebas. Pilih Orang ketiga untuk karakter bergaya kotak atau Orang pertama untuk pandangan mata. WASD/panah untuk berjalan, Shift untuk cepat, seret untuk melihat, dan E untuk pintu terdekat. Pada HP gunakan joystick kiri dan seret layar untuk melihat. Esc atau Keluar jelajah kembali ke Orbit. Mode jelajah memakai tabrakan dinding dan akses; tutup/buka gerbang atau tiap pintu geser dua daun plat besi melalui toggle terpisah. Sensor visual mencegah pintu menutup saat karakter ada di jalurnya. Gerakan dan sensor ini adalah simulasi web.</p><h2>Material</h2><p>Tekstur ambientCG berlisensi CC0, tersimpan lokal: 2K untuk desktop dan 1K untuk layar kecil.</p><ul>'''
body+=''.join(f'<li><a href="{html.escape(x["source"])}">{x["id"]}</a> · CC0</li>' for x in m)+'</ul><p><a href="https://docs.ambientcg.com/license/">Lisensi ambientCG</a> · <a href="vendor/LICENSE-three.txt">Lisensi Three.js</a></p>'
body+='<p><a href="./">← Kembali ke viewer</a> · <a href="downloads/NGORO_Detailed_SU2023.skp">Unduh SKP</a></p>'
(R/'web/dist/model-notes.html').write_text('<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NGORO — Catatan model</title><style>body{max-width:780px;margin:60px auto;padding:0 24px;background:#f7f6ee;color:#293c32;font:16px/1.8 system-ui}h1{font:40px Georgia}h2{margin-top:36px;font-size:20px}a{color:#365f49}li{margin:10px 0}</style>'+body+'</html>',encoding='utf-8')
(R/'outputs/README.txt').write_text('NGORO — MODEL & WEB\n\nBuka NGORO_Detailed_SU2023.skp dengan SketchUp 2023 atau lebih baru.\n8 scene tersimpan, 23 tag kelompok, tekstur warna tertanam.\n\nWebsite: https://ngoro-digital-twin.takashimurachan.chatgpt.site\nRevisi 04: puncak atap gudang 12 m dari lantai, karakter web 170 cm, dan pintu dua daun geser plat besi penuh. Fitur revisi sebelumnya tetap tersedia. Status publikasi dicatat di STATE.md.\n\nAsumsi dan sumber: model-manifest.json dan halaman Catatan model.\nBagian tanpa detail DWG adalah interpretasi visual, bukan dokumen rekayasa.\n',encoding='utf-8')
print('Notes and material attribution written')
